export const PLAYER_COLORS = [
  '#ff4d8d',
  '#55d6be',
  '#f7c948',
  '#8b5cf6',
  '#60a5fa',
  '#f97316',
];

export const inventoryCatalog = {
  brassKey: {
    id: 'brassKey',
    label: 'Brass Key',
    icon: 'key',
    description: 'Warm from the parlor cabinet. It has a tiny moon stamped into the handle.',
  },
  pantryCard: {
    id: 'pantryCard',
    label: 'Recipe Card',
    icon: 'card',
    description: 'A stained card that turns ingredient counts into a cabinet code.',
  },
  mirrorShard: {
    id: 'mirrorShard',
    label: 'Mirror Shard',
    icon: 'mirror',
    description: 'A crescent of mirror. It reveals backwards writing when used in the attic.',
  },
  redToken: {
    id: 'redToken',
    label: 'Red Arcade Token',
    icon: 'token',
    description: 'A cherry-red token from the attic cabinet. It hums near the final door.',
  },
  velvetRibbon: {
    id: 'velvetRibbon',
    label: 'Velvet Ribbon',
    icon: 'ribbon',
    description: 'The ribbon ties the whole trail together. The final door wants the marked letters.',
  },
};

export const puzzles = {
  parlorCabinet: {
    id: 'parlorCabinet',
    title: 'The Parlor Cabinet',
    prompt:
      'The matchbox says: CANDLES / MOONS / UMBRELLAS. Count those three things in the parlor tableau and enter the digits in that order.',
    placeholder: '3 digits',
    answer: ['412'],
    success: 'The cabinet latch clicks. Inside: a brass key and a note that says “The first final digit is 4.”',
    hints: ['The matchbox gives the order, not the answer.', 'There are 4 candles, 1 moon, and 2 umbrellas.'],
    grants: ['brassKey'],
    finalDigit: '4',
  },
  recipeLock: {
    id: 'recipeLock',
    title: 'The Pantry Lock',
    prompt:
      'The recipe card says: SALT before SUGAR. OLIVE after CHERRY. Read the ingredient labels in that exact order and enter the 4-digit pantry code.',
    placeholder: '4 digits',
    answer: ['7352'],
    success: 'The pantry opens. You find a mirror shard and a second final digit: 7.',
    hints: ['Collect the recipe card first.', 'Salt = 7, Sugar = 3, Cherry = 5, Olive = 2. The card tells the order.'],
    requires: ['brassKey', 'pantryCard'],
    grants: ['mirrorShard'],
    finalDigit: '7',
  },
  arcadeSequence: {
    id: 'arcadeSequence',
    title: 'The Cabinet Sequence',
    prompt:
      'The sticky note says “Play what the ghosts point at.” In the attic, follow the pointing hands: STAR, EYE, SNAKE, MOON. Convert them using the cabinet labels.',
    placeholder: '4 digits',
    answer: ['9216'],
    success: 'The arcade cabinet coughs out a red token. A third final digit glows: 9.',
    hints: ['Use the mirror shard on the cracked mirror to translate the symbols.', 'STAR 9, EYE 2, SNAKE 1, MOON 6.'],
    requires: ['mirrorShard'],
    grants: ['redToken'],
    finalDigit: '9',
  },
  finalDoor: {
    id: 'finalDoor',
    title: 'The Odd Door',
    prompt:
      'The final lock wants the four digits you earned, then the ribbon letter. Parlor digit + Pantry digit + Arcade digit + the ribbon’s marked letter converted to its alphabet number.',
    placeholder: 'Final code',
    answer: ['4792'],
    success:
      'The wallpaper peels open like a curtain. You escaped The Midnight Curio.',
    hints: ['The record player whispers the first three digits.', 'The ribbon says B. B is the 2nd letter of the alphabet.'],
    requires: ['brassKey', 'mirrorShard', 'redToken', 'velvetRibbon'],
    ending: true,
  },
};

export const rooms = [
  {
    id: 'parlor',
    name: 'The Velvet Parlor',
    kicker: 'Room 1 of 3',
    mood: 'A search-and-find parlor where every object looks a little too intentional.',
    objective: 'Find the cabinet code and take the brass key.',
    palette: 'parlor',
    nextRequirement: 'Solve the Parlor Cabinet to unlock the Kitchen.',
    hotspots: [
      {
        id: 'invitation',
        label: 'Black Envelope',
        x: 16,
        y: 78,
        w: 9,
        h: 9,
        shape: 'envelope',
        title: 'The Invitation',
        body:
          '“Tonight’s little gathering begins with three counts. The matchbox tells the order. Do not trust the portraits. They stare back.”',
      },
      {
        id: 'matchbox',
        label: 'Red Matchbox',
        x: 43,
        y: 73,
        w: 8,
        h: 6,
        shape: 'matchbox',
        title: 'Red Matchbox',
        body:
          'The matchbox is printed with three words: CANDLES / MOONS / UMBRELLAS. Someone underlined them twice.',
      },
      {
        id: 'cabinet',
        label: 'Locked Curio Cabinet',
        x: 63,
        y: 44,
        w: 18,
        h: 32,
        shape: 'cabinet',
        title: 'Locked Curio Cabinet',
        body:
          'A three-digit brass lock hangs on the cabinet. The tiny label reads: “Count the room. Obey the matchbox.”',
        puzzle: 'parlorCabinet',
      },
      {
        id: 'portrait',
        label: 'Blinking Portrait',
        x: 31,
        y: 21,
        w: 18,
        h: 23,
        shape: 'portrait',
        title: 'Blinking Portrait',
        body:
          'The painted eyes move, but the frame gives you nothing useful. Rude.',
      },
      {
        id: 'clock',
        label: 'Moon Clock',
        x: 53,
        y: 18,
        w: 9,
        h: 12,
        shape: 'clock',
        title: 'Moon Clock',
        body:
          'The clock has one moon on its face. It is stuck at 12:04, which feels accusatory.',
      },
      {
        id: 'umbrella1',
        label: 'Umbrella Stand',
        x: 81,
        y: 64,
        w: 10,
        h: 25,
        shape: 'umbrella',
        title: 'Umbrella Stand',
        body: 'Two umbrellas lean together. One has teeth painted on the handle.',
      },
      {
        id: 'candleCluster',
        label: 'Four Candles',
        x: 10,
        y: 46,
        w: 18,
        h: 22,
        shape: 'candles',
        title: 'Mantel Candles',
        body: 'Four candles. One flame bends toward the cabinet, even though there is no breeze.',
      },
      {
        id: 'teacups',
        label: 'Stacked Teacups',
        x: 48,
        y: 55,
        w: 12,
        h: 14,
        shape: 'teacups',
        title: 'Stacked Teacups',
        body:
          'The cups are arranged from largest to smallest. You hear a tiny clink from inside, but nothing moves.',
      },
    ],
  },
  {
    id: 'kitchen',
    name: 'The Whisper Kitchen',
    kicker: 'Room 2 of 3',
    mood: 'A midnight kitchen full of mislabeled jars, coded recipes, and aggressively suspicious olives.',
    objective: 'Use the brass key, solve the recipe lock, and collect the mirror shard.',
    palette: 'kitchen',
    nextRequirement: 'Solve the Pantry Lock to unlock the Attic Arcade.',
    lockedUntil: 'parlorCabinet',
    hotspots: [
      {
        id: 'kitchenDoor',
        label: 'Kitchen Door',
        x: 8,
        y: 24,
        w: 14,
        h: 48,
        shape: 'door',
        title: 'Kitchen Door',
        body:
          'The brass key fits. The next room smells like lemon peel, old wood, and someone’s bad decisions.',
        requires: ['brassKey'],
      },
      {
        id: 'recipeCard',
        label: 'Recipe Card',
        x: 43,
        y: 64,
        w: 12,
        h: 10,
        shape: 'recipe',
        title: 'Recipe Card',
        body:
          '“For the pantry: SALT before SUGAR. OLIVE after CHERRY. The jars know their numbers. The lock likes order.”',
        grants: ['pantryCard'],
      },
      {
        id: 'ingredientShelf',
        label: 'Ingredient Shelf',
        x: 26,
        y: 19,
        w: 42,
        h: 23,
        shape: 'shelf',
        title: 'Ingredient Shelf',
        body:
          'Four labels matter: SALT is marked 7. SUGAR is marked 3. CHERRY is marked 5. OLIVE is marked 2.',
      },
      {
        id: 'pantry',
        label: 'Locked Pantry',
        x: 72,
        y: 24,
        w: 18,
        h: 53,
        shape: 'pantry',
        title: 'Locked Pantry',
        body:
          'A four-digit lock blocks the pantry. Someone scratched “read the card, not the room” into the paint.',
        puzzle: 'recipeLock',
        requires: ['brassKey', 'pantryCard'],
      },
      {
        id: 'sink',
        label: 'Deep Sink',
        x: 30,
        y: 58,
        w: 17,
        h: 15,
        shape: 'sink',
        title: 'Deep Sink',
        body:
          'The faucet drips once every seven seconds. Dramatic, but not currently useful.',
      },
      {
        id: 'oliveBowl',
        label: 'Olive Bowl',
        x: 58,
        y: 57,
        w: 11,
        h: 12,
        shape: 'olives',
        title: 'Olive Bowl',
        body:
          'An unreasonable number of olives. A toothpick flag says: “OLIVE = 2.”',
      },
      {
        id: 'fridge',
        label: 'Humming Fridge',
        x: 11,
        y: 75,
        w: 20,
        h: 15,
        shape: 'fridge',
        title: 'Fridge Magnet Poem',
        body:
          'The magnets spell “DON’T PANIC.” Then, very slowly, they spell “PANIC LATER.”',
      },
    ],
  },
  {
    id: 'attic',
    name: 'The Attic Arcade',
    kicker: 'Room 3 of 3',
    mood: 'A neon attic where broken toys, backwards notes, and a hungry cabinet guard the exit.',
    objective: 'Solve the arcade cabinet, find the ribbon, and escape through the Odd Door.',
    palette: 'attic',
    nextRequirement: 'Solve the Cabinet Sequence, collect the ribbon, then open the Odd Door.',
    lockedUntil: 'recipeLock',
    hotspots: [
      {
        id: 'atticMirror',
        label: 'Cracked Mirror',
        x: 8,
        y: 17,
        w: 21,
        h: 31,
        shape: 'mirrorWall',
        title: 'Cracked Mirror',
        body:
          'Hold up the mirror shard and the backwards chalk becomes readable: “STAR 9. EYE 2. SNAKE 1. MOON 6.”',
        requires: ['mirrorShard'],
      },
      {
        id: 'stickyNote',
        label: 'Pointing Hands Note',
        x: 38,
        y: 18,
        w: 14,
        h: 11,
        shape: 'sticky',
        title: 'Pointing Hands Note',
        body:
          'A sticky note says: “Play what the ghosts point at: STAR → EYE → SNAKE → MOON.”',
      },
      {
        id: 'arcade',
        label: 'Hungry Arcade Cabinet',
        x: 58,
        y: 25,
        w: 22,
        h: 50,
        shape: 'arcade',
        title: 'Hungry Arcade Cabinet',
        body:
          'The screen flashes four symbol buttons. It will only accept numbers. Something nearby translates symbols into digits.',
        puzzle: 'arcadeSequence',
        requires: ['mirrorShard'],
      },
      {
        id: 'velvetRibbon',
        label: 'Velvet Ribbon',
        x: 83,
        y: 80,
        w: 10,
        h: 8,
        shape: 'ribbon',
        title: 'Velvet Ribbon',
        body:
          'The ribbon tag says: “Final letter: B.” B is the 2nd letter of the alphabet.',
        grants: ['velvetRibbon'],
      },
      {
        id: 'oddDoor',
        label: 'The Odd Door',
        x: 35,
        y: 39,
        w: 18,
        h: 43,
        shape: 'oddDoor',
        title: 'The Odd Door',
        body:
          'The final door has a four-character keypad. It wants every earned digit plus the ribbon’s letter-number.',
        puzzle: 'finalDoor',
        requires: ['brassKey', 'mirrorShard', 'redToken', 'velvetRibbon'],
      },
      {
        id: 'toybox',
        label: 'Toybox',
        x: 15,
        y: 63,
        w: 18,
        h: 16,
        shape: 'toybox',
        title: 'Toybox',
        body:
          'Inside: a wooden snake, a plastic moon, and a note that just says “not everything is a clue.” Annoying but fair.',
      },
      {
        id: 'recordPlayer',
        label: 'Dusty Record Player',
        x: 47,
        y: 77,
        w: 22,
        h: 12,
        shape: 'record',
        title: 'Dusty Record Player',
        body:
          'The record whispers: “Four. Seven. Nine. Then the ribbon.” Useful? Extremely.',
      },
    ],
  },
];

export const initialGameState = {
  roomIndex: 0,
  inventory: {},
  solved: {},
  finalDigits: {},
  ending: false,
  startedAt: null,
};

export const normalizeAnswer = (value) =>
  value.toString().toLowerCase().replace(/[^a-z0-9]/g, '').trim();
